name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup Java 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: build
      run:  ./gradlew clean build

    - name: release
      run: |
        sed -n "/^## \[$GITHUB_REF_NAME\]/,/^##/p" CHANGELOG.md | grep -v "^## \[" > changelog.txt
        gh release create $GITHUB_REF_NAME --notes-file changelog.txt build/libs/*
      env:
        GH_TOKEN: ${{ github.token }}
